MOD_CFLAGS+=-D__KERNEL__ -DLINUX -D__linux__ \
    -DMEI_DRV_ATM_PTM_INTERFACE_ENABLE=1 \
    -DMEI_INTERN -DMEI_MEI_SW_EMUL=0 -DIKOS_EMULATION=0 -DIKOS_BUSY_TIMEOUT=0 \
    -DMEI_MAX_DFEX_ENTITIES=1 -DMEI_MAX_DFE_INSTANCE_PER_ENTITY=1 \
    -DMEI_SUPPORT_DEVICE_VINAX=0 -DMEI_SUPPORT_DEVICE_VR9=1 \
    -DMEI_SUPPORT_DEVICE_AR9=0 -DDEBUG_PRINT -DERROR_PRINT \
    -DMEI_DRV_IFXOS_ENABLE=0 -DMEI_SUPPORT_DSM=1
